### ISSUE TITLE
Need help with underscore support in TS/JS?

### ISSUE THREAD

**Issue by dbalatero** [jetify-com/typeid#33]
👋! Our team at [Graphite](https://graphite.dev) would love to get underscore support in the official TypeScript/JS library.

Do you need help implementing this? If it's straightforward we might be able to land a patch and accelerate to the `v0.3` spec, like you did for Go: https://github.com/jetify-com/typeid/commit/5ffabce2e339d4f390b4672711f29d22d34dd27c

**Comment by loreto** [comment]
@LucilleH Are you already working on this? Or can the graphite team send us a PR? (if they can send us a PR, let's give them a few pointers)

**Comment by dbalatero** [comment]
@savil We just started using it as a default for our IDs :) and we had a thread today where we were struggling with naming:

> for the new prefix-ed db ids, is there a standard we want to apply for prefixes? I'm trying to come up with a prefix for `SelfTestRunTest`. `selftestruntest` seems a bit long and strange without separators and `strt` seems semi random and may overlap something else long term

so I'm glad to see that underscore support just landed in time!

**Comment by LucilleH** [comment]
@dbalatero I’m planning to implement it tomorrow. If you already have a patch feel free to put out a PR in the jetify-com/opensource repo under typeid/typeid-js folder. If not, rest assured it will be out soon 😃

**Comment by loreto** [comment]
Closing

**Comment by savil** [comment]
@dbalatero love Graphite - thank you for making it 🙏🏾
