### ISSUE TITLE
Created a Postgres extension for TypeID

### ISSUE THREAD

**Issue by blitss** [jetify-com/typeid#34]
Hi there,
Just wanted to put this out there that I created an extension for Postgres which allows to use TypeIDs as any other IDs: https://github.com/blitss/typeid-postgres-extension

It's based on the code from @conradludgate and also passes the tests you had.

It stores them as prefixes + 128-bit UUIDs under the hood and returns them as human-readable IDs; allows to use ID as primary key as well sort it/ filter it/convert back and forth to uuid.

I'm not very proficient with Rust but according to my tests it should be fine to use and better than sql implementation (https://github.com/jetify-com/typeid-sql) due to it being an extension and implementing wider subset of postgres features.

**Comment by blitss** [comment]
> @blitss Thank you for sharing this, this is awesome. I've been wanting someone to write a postgres extension for a while. I'm glad you took it on!
> 
> I think we should go ahead and advertise your extension in the typeid README. Do you want to go ahead and send me a PR against: https://github.com/jetify-com/opensource/blob/main/typeid/typeid/README.md ?

sure! https://github.com/jetify-com/opensource/pull/342

**Comment by loreto** [comment]
Approved PR. Closing.
